apiVersion: v1
kind: Service
metadata:
  name: example-application
  labels:
    app: example-application
spec:
#  type: ClusterIP
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 30080
  selector:
    app: example-application

